type=armor
weight=100
items=minecraft:diamond_chestplate
texture.leather_layer_1=assets/minecraft/optifine/cit/items/slimefun/technical_gadgets/parachute/armor
texture.leather_layer_1_overlay=assets/minecraft/optifine/cit/items/slimefun/technical_gadgets/parachute/armor
components.minecraft\:custom_data.PublicBukkitValues.*=PARACHUTE