type=item
items=polished_andesite
texture=quintuple_compressed_cobblestone
model=quintuple_compressed_cobblestone
components.minecraft\:custom_name=ipattern:Quintuple Compressed Cobblestone
weight=100