name: Create Release

on: 
  push:
    branches: [ "textures" ]
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'slimefun-textures.zip'
        exclusions: '*.git*'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "slimefun-textures.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ secrets.VERSION }}
