name: Create Release

on: 
  push:
    branches: [ "textures" ]
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get next version
      uses: reecetech/version-increment@2022.10.3
      id: version
      with:
        scheme: semver
        increment: patch
    - name: Archive Release (LIGHT)
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'slimefun-textures-light.zip'
        exclusions: '*.git* *slimefun-textures-dark.zip /assets/minecraft/optifine/cit/slimefun/gui/default/dark/* /assets/minecraft/optifine/cit/slimefun/gui/cargo/dark/* /assets/minecraft/optifine/cit/networks/gui/dark/*'
    - name: Archive Release (DARK)
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'slimefun-textures-dark.zip'
        exclusions: '*.git* *slimefun-textures-light.zip /assets/minecraft/optifine/cit/slimefun/gui/default/light/* /assets/minecraft/optifine/cit/slimefun/gui/cargo/light/* /assets/minecraft/optifine/cit/networks/gui/light/*'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "slimefun-textures-light.zip,slimefun-textures-dark.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.version.outputs.version }}
